import type { NodeType } from '../types/cloud'

export const SCAN_KEY_TO_TYPE: Record<string, NodeType> = {
  'ec2:instances':       'ec2',
  'ec2:vpcs':            'vpc',
  'ec2:subnets':         'subnet',
  'ec2:security-groups': 'security-group',
  'igw':                 'igw',
  'nat':                 'nat-gateway',
  'rds':                 'rds',
  's3':                  's3',
  'lambda':              'lambda',
  'alb':                 'alb',
  'acm':                 'acm',
  'cloudfront':          'cloudfront',
  'apigw':               'apigw',
  'sqs':                 'sqs',
  'secrets':             'secret',
  'ecr':                 'ecr-repo',
  'sns':                 'sns',
  'dynamo':              'dynamo',
  'ssm':                 'ssm-param',
  'r53':                 'r53-zone',
  'sfn':                 'sfn',
  'eventbridge':         'eventbridge-bus',
  'ses':                 'ses',
  'cognito':             'cognito',
  'kinesis':             'kinesis',
  'ecs':                 'ecs',
  'elasticache':         'elasticache',
}
