import type { NodeType } from '@riftview/shared'

export const SCAN_KEY_TO_TYPE: Record<string, NodeType> = {
  'ec2:instances': 'aws:ec2',
  'ec2:vpcs': 'aws:vpc',
  'ec2:subnets': 'aws:subnet',
  'ec2:security-groups': 'aws:security-group',
  igw: 'aws:igw',
  nat: 'aws:nat-gateway',
  rds: 'aws:rds',
  s3: 'aws:s3',
  lambda: 'aws:lambda',
  alb: 'aws:alb',
  acm: 'aws:acm',
  cloudfront: 'aws:cloudfront',
  apigw: 'aws:apigw',
  sqs: 'aws:sqs',
  secrets: 'aws:secret',
  ecr: 'aws:ecr-repo',
  sns: 'aws:sns',
  dynamo: 'aws:dynamo',
  ssm: 'aws:ssm-param',
  r53: 'aws:r53-zone',
  sfn: 'aws:sfn',
  eventbridge: 'aws:eventbridge-bus',
  ses: 'aws:ses',
  cognito: 'aws:cognito',
  kinesis: 'aws:kinesis',
  ecs: 'aws:ecs',
  elasticache: 'aws:elasticache',
  eks: 'aws:eks',
  opensearch: 'aws:opensearch',
  msk: 'aws:msk'
}
